{% set name = "wagtail-sharing" %}
{% set version = "2.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 939e533ca25ceb7c6ae125544a9b4e83da32f9009f765c56b24c2d70957042aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=43.0.0
    - wheel
    - pip
  run:
    - django
    - python >={{ python_min }}
    - wagtail >=6.2

test:
  imports:
    - wagtailsharing
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Easier sharing of Wagtail drafts
  home: https://github.com/cfpb/wagtail-sharing
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
